Mission2/Models/GradeCalculatorModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Mission2.Models
{
    public class GradeCalculatorModel
    {
        //This is another spot where we are ensuring that the data entered is in the appropraite range, this section will give the user and error if they try to input an invalid number.
        [Required]
        [Range(0, 100, ErrorMessage = "Enter number between 0 to 100")]
        public string Assignments { get; set; }
        [Required]
        [Range(0, 100, ErrorMessage = "Enter number between 0 to 100")]
        public string GroupProjects { get; set; }
        [Required]
        [Range(0, 100, ErrorMessage = "Enter number between 0 to 100")]
        public string Quizzes { get; set; }
        [Required]
        [Range(0, 100, ErrorMessage = "Enter number between 0 to 100")]
        public string Exams { get; set; }
        [Required]
        [Range(0, 100, ErrorMessage = "Enter number between 0 to 100")]
        public string Intex { get; set; }

    }
}

Mission2/Controllers/BlahController.cs
using Microsoft.AspNetCore.Mvc;
using Mission2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission2.Controllers
{
    //Maps the user to the index page upon arrival at the site.
    public class BlahController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        //This section sends something different based upon the request method, when getting the page it sends back the HTML, when posting it passes the information collected in the form.
        [HttpGet]
        public IActionResult GradeCalculator()
        {
            return View();
        }
        [HttpPost]
        public IActionResult GradeCalculator(GradeCalculatorModel model)
        {
            return View();
        }
    }
}

Mission2/Views/Blah/GradeCalculator.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model GradeCalculatorModel;

<br />
<br />
<h3>Grade Calculator</h3>
<form method="post">
    <!--This is the form where information is entered for the calculator and is passed through C# to the appropriate model/location.-->
    <label>Assignments :</label>
    <input id="txtAssignments"  asp-for="Assignments" />
    <br />
    <label>Group Projects:</label>
    <input id="txtGroupProjects"  asp-for="GroupProjects" />
    <br />
    <label>Quizzes:</label>
    <input id="txtQuizzes" asp-for="Quizzes" />
    <br />
    <label>Exams:</label>
    <input id="txtExams" asp-for="Exams" />
    <br />
    <label>INTEX :</label>
    <input id="txtIntex"  asp-for="Intex" />
    <br />
    <input id="btnCalc" type="submit" value="Calculate Grade" />
    <div asp-validation-summary="All"></div>

</form>
<br />
<br />
<script src="~/js/myCupofJavaScript.js"></script>

Mission2/Views/Blah/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Nathan Anderson";
}

<h1>Nathan Anderson</h1>
<img src="img/IMG_8724.JPG" class="center" />
<p>
    I have absolutely loved all of my programming classes thus far and am very excited to add another programming language to my resume!
    I currently want to go into development when I graduate and I've been wanting to learn a strongly typed language, this is going to be a great
    opportunity. I am also excited to be using a different program to write the code so that I can increase my experience with different applications!
</p>
<h3>Top 3 Jobs I am most interested in pursuing.</h3>
<div class="center">
    <ol>
        <li>Developer/Project Manager at Microsoft</li>
        <li>Developer/Project Manager at Adobe</li>
        <li>Security Consultant at EY</li>
    </ol>
</div>

Mission2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <link href="~/css/default.css" rel="stylesheet" />
    <meta charset="utf-8" />
    <link rel="icon" type="image/x-icon" href="img/icon.png" />
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <title>@ViewData["Title"]</title>
</head>
<body>
    <nav>
        <a asp-controller="Blah" asp-action="Index">Home</a>
        <a asp-controller="Blah" asp-action="GradeCalculator">Grade Calculator</a>

    </nav>
    <script src="~/lib/jquery/jquery-3.6.0.min.js"></script>

    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
    <div>
        @RenderBody()
    </div>
</body>
</html>